repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Nazmul Islam
title: Trainee DevOps and Cloud Engineering
email: nazmulislam76bd@gmail.com
website: https://nazmulpranto76.github.io/nazmul_islam_resume/

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  NazmulPranto76


# Additional icon links
additional_links:
- title: discord
  icon: fab fa-discord (https://fontawesome.com/icons/discord?f=brands&s=solid)
  url:  https://discord.com/users/765420390041387058
  
- title: facebook
  icon: fab fa-facebook (https://fontawesome.com/icons/facebook?f=brands&s=solid)
  url: https://www.facebook.com/nazmul.pranto.31/  
  
- title: HackerRank
  icon: fab fa-hackerrank (https://fontawesome.com/icons/hackerrank?f=brands&s=solid)
  url: https://www.hackerrank.com/nazmulislam76bd
  
- title: LeetCode
  icon: fas fa-globe
  url: https://leetcode.com/nazmulislam/ 
  
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Nazmul Islam and I'm a recent Computer Science graduate who is highly motivated and eager to work in a professional setting. An enthusiastic person who is well dedicated to his craft. I am constantly developing and striving to be the best in the field.

  Currently, I am learning <mark>Django</mark> and also, studying to become a <mark>DevOps and Cloud Engineer</mark>.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Hotel Management System
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          This is a simple academic project I have completed under software engineering course using <mark>JAVA</mark> and <mark>MVC</mark> architectural pattern.
#     content:
#       - layout: left
        title: R-BLOG
        description: | # this will include new lines to allow paragraphs
          A blog-based project using <mark>HTML</mark>, <mark>CSS</mark>, <mark>JavaScript</mark> and <mark>Django</mark> framework. I started this project as a way to learn about <mark>Django</mark>. Currently, working on it to add more features.
#     content:
#       - layout: left
        title: Buy-It
        description: | # this will include new lines to allow paragraphs
          An E-commerce project mainly based on <mark>Django</mark>, <mark>Bootstrap</mark>, and <mark>JavaScript</mark>. I wanted to learn how an E-commerce website works and try to implement <mark>REST</mark> api in this project.
#     content:
#       - layout: top-left
        title: Thesis Project
        description: | # this will include new lines to allow paragraphs
          **Surveillance in Maritime Scenario Using Deep-Learning and Swarm Intelligence**.
          
          This is my thesis project for drone-based rescue operations using swarm algorithm and object detection CNN model.


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: BRAC University
        link: https://www.bracu.ac.bd/
        # link_text: boringcompany.com
        sub_title: Student Tutor
        caption: June 2021 - April 2022
#         quote: >
#           Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Served as Student Tutor in Artificial Intelligence-(8 months) and Programming Language-(4 months) courses. Tasked with teaching students about basic concepts of artificial intelligence, machine learning, and basics of python and OOP.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: BRAC University
        caption: 2018 - 2022
        sub_title: BSc Computer Science and Engineering
#         quote: >
#           Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at the university, I learned most of my theoretical and practical skills. I also learned about teamwork and working to tight deadlines. I thoroughly enjoyed my time at university and learned a lot about a healthy work-life balance.

          I also spent my free time as a *Senior Executive* and was one of the founding members of the *FINACT Club*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in technologies and software engineering some of my other interests and hobbies are:
      - Reading
      - Gaming
      - Eating
      
#      -[Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

#       Look at this cool image  
#       ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
